#!/usr/bin/env python3
"""Prepare a Flutter-generated Xcode project for Firebase Test Lab.

Two edits, both on `ios/Runner.xcodeproj/project.pbxproj`:

1. Point every PRODUCT_BUNDLE_IDENTIFIER at a bundle id the signing team
   actually owns. `flutter create` defaults to com.example.*, which cannot be
   registered, so automatic signing would fail before the build starts.

2. Swap the scaffolded RunnerTests.swift for an Objective-C runner that uses
   integration_test's INTEGRATION_TEST_IOS_RUNNER macro. The macro reflects
   every Dart integration test into its own XCTest case, which is what makes
   Test Lab report them individually. The Swift API that would avoid this swap
   is deprecated and collapses the whole suite into one case.

Exits non-zero only on a genuinely broken project, so the caller can decide
whether an unpatched project should still attempt an unsigned build.
"""
import argparse
import pathlib
import re
import sys

RUNNER_OBJC = """// Generated by AppRunner. Reflects each Dart integration test into its own
// XCTest case so Firebase Test Lab reports them individually.
@import XCTest;
@import integration_test;

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
"""


def log(message):
    print(f"[patch_xcode] {message}", file=sys.stderr)


def set_bundle_ids(pbx_text, bundle_id):
    """Rewrites bundle ids, preserving the .RunnerTests suffix on the test target."""
    def replace(match):
        current = match.group(1).strip()
        suffix = ".RunnerTests" if current.endswith(".RunnerTests") else ""
        return f"PRODUCT_BUNDLE_IDENTIFIER = {bundle_id}{suffix};"

    patched, count = re.subn(r"PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);", replace, pbx_text)
    log(f"set {count} bundle identifier entries to {bundle_id}")
    return patched


def use_objc_runner(pbx_text, tests_dir):
    """Replaces RunnerTests.swift with RunnerTests.m, in the project and on disk."""
    swift_file = tests_dir / "RunnerTests.swift"
    objc_file = tests_dir / "RunnerTests.m"

    objc_file.write_text(RUNNER_OBJC)

    if "RunnerTests.swift" not in pbx_text:
        if "RunnerTests.m" in pbx_text:
            log("project already references RunnerTests.m")
            return pbx_text, True
        log("project references neither RunnerTests.swift nor RunnerTests.m")
        return pbx_text, False

    # The scaffold declares the file once and builds it once; both references
    # carry the same name, so a plain rename covers them.
    patched = pbx_text.replace("RunnerTests.swift", "RunnerTests.m")
    patched = patched.replace(
        "lastKnownFileType = sourcecode.swift; path = RunnerTests.m;",
        "lastKnownFileType = sourcecode.c.objc; path = RunnerTests.m;",
    )

    if "lastKnownFileType = sourcecode.c.objc; path = RunnerTests.m;" not in patched:
        log("could not retype the RunnerTests file reference")
        return pbx_text, False

    if swift_file.exists():
        swift_file.unlink()
    log("switched RunnerTests to the Objective-C integration runner")
    return patched, True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ios-dir", required=True)
    parser.add_argument("--bundle-id", required=True)
    args = parser.parse_args()

    ios_dir = pathlib.Path(args.ios_dir)
    pbx_path = ios_dir / "Runner.xcodeproj" / "project.pbxproj"
    tests_dir = ios_dir / "RunnerTests"

    if not pbx_path.exists():
        log(f"missing {pbx_path}")
        return 1
    if not tests_dir.is_dir():
        log(f"missing {tests_dir}; the project has no RunnerTests target")
        return 1

    text = pbx_path.read_text()
    text = set_bundle_ids(text, args.bundle_id)
    text, runner_ok = use_objc_runner(text, tests_dir)
    pbx_path.write_text(text)

    # Reported so the workflow can skip Test Lab with an accurate reason rather
    # than letting xcodebuild fail in a way that reads like a code failure.
    print(f"runner_patched={'true' if runner_ok else 'false'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
