#!/usr/bin/env bash
#
# Brings an arbitrary Flutter project up to the shape the iOS pipeline needs:
# an iOS runner with a RunnerTests target, an integration test to drive, and a
# bundle identifier the signing team owns.
#
# Everything it adds is additive and generated only when missing, so a project
# that already ships its own iOS setup and integration tests is left alone.
#
# Usage: prepare_project.sh <app-dir> <bundle-id> <org>
set -euo pipefail

APP_DIR="${1:?usage: prepare_project.sh <app-dir> <bundle-id> <org>}"
BUNDLE_ID="${2:?usage: prepare_project.sh <app-dir> <bundle-id> <org>}"
ORG="${3:-com.example}"

log() { printf '\033[1;36m[prepare]\033[0m %s\n' "$*" >&2; }

# Resolve before the cd below, or the relative path stops pointing here.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$APP_DIR"

PKG="$(python3 -c "
import re, sys
text = open('pubspec.yaml').read()
match = re.search(r'^name:\s*([A-Za-z0-9_]+)', text, re.M)
sys.stdout.write(match.group(1) if match else '')
")"
[[ -n "$PKG" ]] || { log "could not read the package name from pubspec.yaml"; exit 1; }
log "package: ${PKG}"

# ── iOS platform folder ─────────────────────────────────────────────────────
# `flutter create` on an existing project fills in only what is missing, so it
# is safe to run whether ios/ is absent or merely lacks the tests target.
if [[ ! -d ios ]]; then
  log "no ios/ directory; generating one"
  flutter create --platforms=ios --org "$ORG" --project-name "$PKG" .
elif [[ ! -d ios/RunnerTests ]]; then
  log "ios/ has no RunnerTests target; regenerating the iOS scaffold"
  flutter create --platforms=ios --org "$ORG" --project-name "$PKG" .
else
  log "ios/ already has a RunnerTests target"
fi

# ── integration_test dependency ─────────────────────────────────────────────
python3 - "$PWD/pubspec.yaml" <<'PY'
import re
import sys

path = sys.argv[1]
text = open(path).read()

if re.search(r'^\s+integration_test\s*:', text, re.M):
    print('[prepare] integration_test already in pubspec.yaml', file=sys.stderr)
elif re.search(r'^dev_dependencies:', text, re.M):
    text = re.sub(
        r'^dev_dependencies:\s*\n',
        'dev_dependencies:\n  integration_test:\n    sdk: flutter\n',
        text,
        count=1,
        flags=re.M,
    )
    open(path, 'w').write(text)
    print('[prepare] added integration_test to dev_dependencies', file=sys.stderr)
else:
    open(path, 'a').write('\ndev_dependencies:\n  integration_test:\n    sdk: flutter\n')
    print('[prepare] created dev_dependencies with integration_test', file=sys.stderr)
PY

# ── integration test ────────────────────────────────────────────────────────
# Test Lab needs at least one Dart integration test to reflect into XCTest. A
# project without one gets a launch smoke test: it proves the app boots and
# renders on a real device, which is exactly what the device stage is for.
mkdir -p integration_test
if compgen -G "integration_test/*.dart" >/dev/null; then
  log "using the project's own integration tests"
else
  if [[ ! -f lib/main.dart ]]; then
    log "no lib/main.dart to drive; cannot generate a smoke test"
    exit 1
  fi
  log "no integration tests found; generating a launch smoke test"
  cat > integration_test/app_test.dart <<DART
// Generated by AppRunner because the project ships no integration tests.
// Replace it with your own: anything under integration_test/ is used as-is.
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:${PKG}/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('app launches and settles', (tester) async {
    app.main();

    // A launch that throws, hangs, or renders nothing fails here — the three
    // things a simulator-free unit test suite cannot tell you.
    await tester.pumpAndSettle(const Duration(seconds: 10));

    expect(find.byType(WidgetsApp), findsOneWidget);
  });
}
DART
fi

# ── Xcode project ───────────────────────────────────────────────────────────
PATCH_OUT="$(python3 "${SCRIPT_DIR}/patch_xcode.py" --ios-dir "$PWD/ios" --bundle-id "$BUNDLE_ID")"
echo "$PATCH_OUT"

log "prepared ${PKG} for bundle id ${BUNDLE_ID}"
